### ISSUE TITLE
Allow line numbers even if file has local changes

### ISSUE THREAD

**Issue by williamboman** [ruifm/gitlinker.nvim#43] opened 2021-12-22 17:19 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have the option to still include line numbers when producing links to files that have local changes. I feel like most of the time it'd still produce perfectly valid links.

**Describe the solution you'd like**
Either to have an option that allows for line numbers for files with local changes, or perhaps even make this default behavior but with a warning message informing about potential incorrect line numbers because the file has local changes.

**Additional context**
I wonder if it'd be feasible to try to calculate the corresponding remote line numbers by offsetting the each line number with its cumulative line delta? So like, if you're on line 10, and above line 10 there's diffs that adds `+2 -1 = +1` lines - so the remote line number ought to be 9 (disregarding the fact that the current line might be changed). I just came up with the idea so it's not very thought through haha

**Comment by ruifm** [comment] 2021-12-22 17:50
I think this is a duplicate of https://github.com/ruifm/gitlinker.nvim/issues/26

I'm fine with a temporary change that keeps the warning but still computes the lines though, it should be a simple PR.

**Closed** 2021-12-22 18:18 UTC
Labels: enhancement

**Comment by ruifm** [comment] 2021-12-22 18:21
The linked merged PR does just that: changes the default behavior so that it still computes line numbers but with a warning. I don't reckon an option is warranted for this.

Supporting actually correct line numbers on a changed file is still tracked by #26 which I hope happens some day. Probably the easiest way to do that is to integrate an optional dependency like [gitsigns](https://github.com/lewis6991/gitsigns.nvim) and use its public hunks API to compute the correct offsets for the lines.

**Comment by williamboman** [comment] 2021-12-22 18:32
Wow that was fast, thanks!

**Comment by williamboman** [comment] 2021-12-23 11:40
It seems like the warning message is always displayed. Everything seems fine in #45 so I'm a bit puzzled. Are you getting the same?

**Comment by ruifm** [comment] 2021-12-23 12:17
> It seems like the warning message is always displayed. Everything seems fine in #45 so I'm a bit puzzled. Are you getting the same?

I think https://github.com/ruifm/gitlinker.nvim/pull/46 finally fixes it. There was some funky logic that needed to be updated related to the `git diff` call after https://github.com/ruifm/gitlinker.nvim/pull/40, my bad!
