### ISSUE TITLE
remote URI parsing fails when it does not end in `.git`

### ISSUE THREAD

**Issue by tjdevries** [ruifm/gitlinker.nvim#2] opened 2021-04-12 19:39 UTC
```lua
local function parse_uri(uri, errs)
    local chars = "[_%-%w%.]+"
    local protocol_schema = "%g+[/@]"
    local host_schema = chars .. "%." .. chars
    local path_schema = "" .. chars .. "/" .. chars
    local host_capture = protocol_schema .. '(' .. host_schema .. ")[:/]" ..
                             path_schema .. "%.git$"
    local path_capture = protocol_schema .. host_schema .. "[:/](" ..
                             path_schema .. ")%.git$"
    local repo = {
        host = uri:match(host_capture),
        path = uri:match(path_capture)
    }
    if not repo.host then
        table.insert(errs, string.format(
                         ": cannot parse the host name from uri '%s'", uri))
    end
    return repo
end
```

So I don't think this code handles something when the remote is something like:

`"https://github.com/nvim-lua/plenary.nvim"`

I'm not sure if there is a generic way to do this or not or if I need to do something special to configure it to do this or not.

Cool plugin though :)

**Comment by tjdevries** [comment] 2021-04-12 19:40
```lua
function M.get_repo(remote)
    local errs = {
        string.format("Failed to retrieve repo data for remote '%s'", remote)
    }
    local remote_uri = get_remote_uri(remote)
    if not remote_uri then
        table.insert(errs, string.format(
                         ": cannot retrieve url from remote '%s'", remote))
        return nil
    end

    local repo = parse_uri(remote_uri, errs)
    if not repo then error(table.concat(errs)) end
    return repo
end
```

btw, this code won't error out because an empty table in lua matches as true. You should use vim.tbl_isempty or similar

**Comment by tjdevries** [comment] 2021-04-12 19:41
Oh, I also noticed:


``lua
        for i in 0, 50 do
            local revspec = "HEAD~" .. i
            if is_rev_in_remote(revspec, remote) then return remote end

        end
```

This should be `for i = 1, 50`, just as a heads up

**Comment by ruifm** [comment] 2021-04-12 21:33
@tjdevries thanks for taking the time to review my first lua plugin, I feel honored!

2 hours live and this happens :man_facepalming: this is what I deserve for not having a test suite yet!

> So I don't think this code handles something when the remote is something like:
> 
> `"https://github.com/nvim-lua/plenary.nvim"`

Weird, I just tried it and it works for me using an https clone... Maybe I'm using a different luajit that has a different lua regex engine?

I'm building neovim with [OpenResty LuaJIT2](https://github.com/openresty/luajit2) (see https://github.com/neovim/neovim/pull/13741), not sure it's that though.

> I'm not sure if there is a generic way to do this or not or if I need to do something special to configure it to do this or not.

If your issue persists and/or it's reproducible by others, I will just hard code a workaround with something like `startswith()`.

> Cool plugin though :)

Thanks!

> ```lua
> function M.get_repo(remote)
>     local errs = {
>         string.format("Failed to retrieve repo data for remote '%s'", remote)
>     }
>     local remote_uri = get_remote_uri(remote)
>     if not remote_uri then
>         table.insert(errs, string.format(
>                          ": cannot retrieve url from remote '%s'", remote))
>         return nil
>     end
> 
>     local repo = parse_uri(remote_uri, errs)
>     if not repo then error(table.concat(errs)) end
>     return repo
> end
> ```
> 
> btw, this code won't error out because an empty table in lua matches as true. You should use vim.tbl_isempty or similar

Neither `repo` or `remote_uri` can currently be an empty table due to the way the functions are constructed, either they are full-formed or `nil` (I think :pray: ). Anyway, better safe than sorry, I will follow your suggestion!

> Oh, I also noticed:
> 
> ```lua
>         for i in 0, 50 do
>             local revspec = "HEAD~" .. i
>             if is_rev_in_remote(revspec, remote) then return remote end
> 
>         end
> ```
> 
> This should be `for i = 1, 50`, just as a heads up

In this case, I want to check `HEAD` itself, i.e. `HEAD~0` (which are the same), as well as the 50 commits before. This is different from

https://github.com/ruifm/gitlinker.nvim/blob/f3e9306bc15f44b97df458b5c98a42111c2daf82/lua/gitlinker/git.lua#L141-L150

where I just want to check the 50 parent commits.

The comment before the loop you pointed out is still wrong since it was copy-pasted, it should state that we are checking HEAD and the previous 50 commits.

The whole 50 commits thing is also a hack anyway (just a strategy to iteratively find a commit that exists in a remote, in case you create a local branch and add a lot of unpushed commits). I don't know any other way of achieving the desired effect cleanly though.

**Comment by tjdevries** [comment] 2021-04-13 11:46
I think you misunderstood:

1. For post 1, I don't have `.git` at the end of the pattern, so it won't match.
2. repo is an empty table because the patterns don't match. you end up with two keys set to nil, which is exactly the same as an empty table.
3. `for i in 1, 50` is not valid lua. You must do `for i = 1, 50` instead. This is a syntax error and will not run.

**Comment by ruifm** [comment] 2021-04-13 12:59
>     1. For post 1, I don't have `.git` at the end of the pattern, so it won't match.

You are right, when I tried to reproduce it, I still cloned with the `.git` at the end (which is the GH default afaik). I really misunderstood, sorry!

Then the reall issue is with `.git`, I will try to address it soon.

>     2. repo is an empty table because the patterns don't match. you end up with two keys set to nil, which is exactly the same as an empty table.

TIL, so a table entry set to nil is the same as if it didn't exist? I must say those semantics are a bit weird for me :laughing: 

>     3. `for i in 1, 50` is not valid lua. You must do `for i = 1, 50` instead. This is a syntax error and will not run.

Yeah,  fortunately that was already fixed by https://github.com/ruifm/gitlinker.nvim/pull/3 !

**Closed** 2021-04-13 16:48 UTC
Labels: bug
